import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "nl";

const translations = {
  en: {
    welcome: "WELCOME TO THE STADIUM",
    searchPlaceholder: "Search a room, shared car...",
    workspaces: "Workspaces",
    sharedMobility: "Shared Mobility",
    neighborhoodEnergy: "Neighborhood & Energy",
    todaySaving: "TODAY: Neighborhood saves",
    inEnergy: "in energy!",
    home: "Home",
    search: "Search",
    bookings: "Bookings",
    account: "Account",
    findRoom: "FIND A ROOM",
    capacity: "Capacity",
    noPreference: "Any",
    date: "Date",
    time: "Time",
    reserve: "RESERVE",
    bookThisRoom: "BOOK THIS ROOM",
    bookingConfirm: "CONFIRM BOOKING",
    bookingConfirmed: "BOOKING CONFIRMED!",
    payAndBook: "PAY & BOOK",
    addMobility: "Add shared mobility?",
    addMobilityDesc: "Add shared mobility options.",
    paymentMethod: "Payment method",
    digitalKey: "Digital Key",
    scanAtEntrance: "Scan at entrance",
    openSmartLock: "OPEN SMART LOCK",
    routeDescription: "GET DIRECTIONS",
    reserveSharedCar: "RESERVE SHARED CAR",
    hours: "hours",
    perHour: "/hr",
    perRide: "per ride",
    free: "Free",
    offerForFree: "Offer for free",
    pricePerRide: "Price per ride (€)",
    confirmMobilityBooking: "Confirm your booking",
    confirmMobilityBookingDesc: "Please review the details below before confirming.",
    totalEstimated: "Total estimated",
    confirmBooking: "Confirm Booking",
    persons: "p",
    wifi: "Wi-Fi",
    projector: "Projector",
    coffee: "Coffee & Drinks",
    tv: "TV",
    available: "Available",
    occupied: "Occupied",
    maintenance: "Maintenance",
    parkingSpaces: "Parking spaces free",
    eBikes: "E-bikes available",
    evChargers: "EV chargers",
    solarOutput: "Solar Output",
    sharedWithNeighbors: "Shared with neighbours",
    co2Saved: "CO₂ Saved Today",
    surplus: "surplus available",
    noMatchToday: "No match today — solar energy shared with community",
    receiving: "Receiving",
    offline: "Offline",
    localNeighbours: "Local Neighbours",
    rent: "Rent",
    backToHome: "Back",
    features: "Features",
    location: "Location",
    stadiumEntrance: "Stadium entrance",
    login: "LOG IN",
    logout: "LOG OUT",
    loggedIn: "Logged in",
    email: "Email",
    password: "Password",
    emailPlaceholder: "your@email.com",
    passwordPlaceholder: "Your password",
    communityCenter: "Community Center",
    localSchool: "Local School",
    residentialBlockA: "Residential Block A",
    sportsClinic: "Sports Clinic",
    cafeDistrict: "Café District",
    northGate: "North Gate",
    eastWing: "East Wing",
    southGate: "South Gate",
    westVIP: "West VIP",
    stadiumMap: "Stadium Map",
    mapHint: "Tap a pin or hover an item",
    facilityParking: "Parking",
    facilityBikeRack: "Bike Rack",
    facilityVipEntrance: "VIP Entrance",
    facilityFirstAid: "First Aid",
    standMain: "Main Stand",
    standFamily: "Family Stand",
    standNorth: "North Stand",
    standSouth: "South Stand",
    mapAvailableHere: "available here",
    inUse: "in use",
    charging: "charging",
    fullyCharged: "Fully charged",
    bike: "Bike",
    electric: "Electric",
    hybrid: "Hybrid",
    noBookings: "No upcoming bookings",
    noBookingsDesc: "Your booked rooms will appear here.",
    noResults: "No results found",
    communityFeedback: "Community Feedback",
    feedbackPlaceholder: "Share your opinion or concern...",
    feedbackExample1: "The new charging stations at the south gate are great!",
    feedbackExample2: "Could we get more solar panels on the east wing?",
    feedbackExample3: "The shared bikes need better maintenance schedules.",
    general: "General",
    facilities: "Facilities",
    mobilityCategory: "Mobility",
    energyCategory: "Energy",
    safety: "Safety",
    you: "You",
    concerns: "Feedback",
    governancePortal: "MULTI-ACTOR GOVERNANCE PORTAL",
    governanceDesc: "Stakeholder collaboration & KPI overview",
    kpiRoomOccupancy: "Room Occupancy",
    kpiParkingUsage: "Parking Usage",
    kpiEnergyShared: "Energy Shared",
    kpiActiveUsers: "Active Users",
    hubManager: "Hub Manager",
    cityCouncil: "City Council",
    energyProvider: "Energy Provider",
    mobilityPartner: "Mobility Partner",
    communityRep: "Community Rep",
    roleOperations: "Operations",
    rolePolicy: "Policy & Planning",
    roleEnergy: "Energy Management",
    roleMobility: "Transport & Parking",
    roleCommunity: "Community Relations",
    stakeholders: "Stakeholders",
    recentActivity: "Recent Activity",
    activityEnergy: "Solar surplus shared with community center",
    activityBooking: "VIP Loge booked for corporate event",
    activityFeedback: "New community feedback received (3)",
    activityParking: "East wing parking at 40% capacity",
    username: "Username",
    usernamePlaceholder: "Your username",
    invalidCredentials: "Invalid username or password. Please try again.",
    wrongPassword: "Incorrect password for Hub Manager account.",
    dashboard: "Dashboard",
    hubManagerHint: "Hub Manager? Log in with your credentials for the governance dashboard.",
    // Booking calendar
    calendarTitle: "Availability Calendar",
    booked: "Booked",
    selectDate: "Select a date to see availability",
    slot: "Slot",
    bookSlot: "Book",
    // Shared mobility
    sharedMobilitySection: "Shared Mobility",
    transportTypes: "Transport Types",
    eBike: "E-Bike",
    eScooter: "E-Scooter",
    sharedCar: "Shared Car",
    carpoolTitle: "Carpool",
    carpoolDesc: "Find or offer rides",
    findRide: "Find a Ride",
    offerRide: "Offer a Ride",
    rideFrom: "From",
    rideTo: "To",
    rideWhen: "When",
    rideSeats: "Seats",
    requestRide: "Request Ride",
    rideRequested: "Ride Requested!",
    bikeRented: "Bike rented! Pick up at",
    reserveCar: "Reserve",
    carReserved: "Car Reserved!",
    sharedCars: "Shared Cars",
    carsAvailable: "available",
    // Reviews
    feedbackExample4: "Parking is often full during events, need more capacity.",
    feedbackExample5: "The VIP lounge is excellent for business meetings.",
    feedbackExample6: "Would love better signage for the shared car spots.",
    feedbackExample7: "Great initiative with solar energy sharing!",
    feedbackExample8: "Safety lighting in the east parking needs improvement.",
    feedbackExample9: "The coworking space Wi-Fi is very reliable.",
    feedbackExample10: "Could we have a shuttle service to the train station?",
    allCategories: "All",
    // Chatbot
    chatbotTitle: "Stadium Assistant",
    chatbotPlaceholder: "Ask a question...",
    chatbotWelcome: "Hi! I'm the Stadium Assistant. How can I help you today?",
    // Invite
    invitePeople: "Invite People",
    inviteDesc: "Invite others to the platform",
    inviteEmail: "Email address",
    inviteEmailPlaceholder: "colleague@email.com",
    inviteRole: "Role",
    inviteUser: "User",
    inviteManager: "Manager",
    sendInvite: "Send Invite",
    inviteSent: "Invite sent!",
    inviteMessage: "Optional message",
    inviteMessagePlaceholder: "Join us at the stadium platform!",
    // Directions
    directionsTitle: "Directions",
    directionsFrom: "UHasselt Building D, Diepenbeek",
    directionsTo: "Mijnstadion Beringen",
    openInMaps: "Open in Google Maps",
    // Carpool rides
    ride1From: "UHasselt",
    ride1To: "Mijnstadion",
    ride1Driver: "Thomas B.",
    ride1Time: "Tomorrow, 08:30",
    ride2From: "Hasselt Station",
    ride2To: "Mijnstadion",
    ride2Driver: "Sarah K.",
    ride2Time: "Tomorrow, 09:00",
    ride3From: "Genk Center",
    ride3To: "Mijnstadion",
    ride3Driver: "Pieter V.",
    ride3Time: "Wed, 14:00",
    // Mobility booking confirmation modal
    mobilityBookingConfirmed: "Booking Confirmed!",
    mobilityBookingDesc: "Your reservation has been added to your upcoming bookings.",
    bikeBookingTitle: "E-Bike Reservation",
    carBookingTitle: "Shared Car Reservation",
    rideBookingTitle: "Carpool Ride",
    viewMyBookings: "View My Bookings",
    close: "Close",
    pickADate: "Pick a date",
    from: "From",
    to: "To",
    invalidTimeRange: "End time must be after start time.",
    inviteToSession: "Invite people to this session",
    inviteToSessionDesc: "Add colleagues by email — they'll receive a calendar invite.",
    addInvitee: "Add",
    inviteesAdded: "invitees added",
    // Login gate
    loginWelcome: "Welcome to Stadium Connect Hub",
    loginSubtitle: "Sign in to continue",
    landingTagline: "Your access to shared mobility, workspaces and local energy",
    signIn: "Sign In",
    signUp: "Sign Up",
    register: "Register",
    createAccount: "Create your account",
    alreadyHaveAccount: "Already have an account?",
    noAccountYet: "Don't have an account?",
    fullName: "Full name",
    fullNamePlaceholder: "Your name",
    confirmPassword: "Confirm password",
    passwordsDontMatch: "Passwords do not match.",
    accountCreated: "Account created — please sign in.",
    userAlreadyExists: "An account with this username already exists.",
    backToWelcome: "Back",
    // Room availability
    availableUnits: "available",
    // Ticketshop
    ticketshop: "Ticketshop",
    ticketshopSubtitle: "Buy tickets and top up your card",
    buyTickets: "Buy Tickets",
    consumptionCard: "Consumption Card",
    football: "Football",
    hockey: "Hockey",
    allSports: "All",
    seats: "seats",
    buy: "Buy",
    clubConsumptionCard: "Club Consumption Card",
    currentBalance: "Current balance",
    validForAllSports: "Valid for all sports — Football, Hockey & more.",
    topUpAmount: "Top-up amount",
    customAmount: "Custom amount",
    enterAmount: "Enter amount in €",
    topUpNow: "Top up",
    topUpConfirmed: "Card topped up",
    purchaseConfirmed: "Purchase Confirmed!",
    matchFootball1: "KVK Beringen vs Lommel SK",
    matchFootball2: "KVK Beringen vs RC Hades",
    matchHockey1: "Beringen Hockey vs HC Hasselt",
    matchHockey2: "Beringen Hockey vs Genk HC",
    ticketshopShort: "Tickets",
    selectSeat: "Select your seat",
    section: "Section",
    row: "Row",
    seat: "Seat",
    selectedSeat: "Selected seat",
    pickSeatFirst: "Pick a section, row and seat to continue",
    chatbotResponseParking: "The stadium has 1,080 parking spaces across 4 zones. Check the Shared Mobility section for real-time availability.",
    chatbotResponseRoom: "We have bookable spaces including VIP Loges, Press Room A, and the Stadium Workspace. Go to Workspaces to browse and book.",
    chatbotResponseEnergy: "The stadium's solar panels generate up to 200 kW. Surplus energy is shared with 5 local neighbours in the community.",
    chatbotResponseBike: "We have 6 e-bikes available at various locations. Check the E-Bike tab in Shared Mobility to rent one.",
    chatbotResponsePrice: "Room prices range from €10/hr (Workspace) to €25/hr (Press Room). VIP Loges start at €15/hr.",
    chatbotResponseCarpool: "You can find Carpool rides under Shared Mobility. Tap the button below to jump straight there.",
    chatbotGoToCarpool: "Open Carpool",
    chatbotFallback: "I can help with questions about parking, rooms, energy, bikes, carpool, and prices. Feel free to ask!",
    // Ticketshop additions
    ticketshopMenu: "Ticketshop",
    upcomingBookings: "Upcoming bookings",
    myTickets: "My tickets",
    reserveSharedCarDesc: "Find an available shared car at the stadium.",
    open: "Open",
    notAvailable: "Not available",
    available_short: "Available",
    bookedAlready: "Already booked for this slot",
    confirmAndPay: "Confirm & pay",
    paymentSummary: "Payment summary",
    total: "Total",
    item: "Item",
    payNow: "Pay now",
    cancel: "Cancel",
    transactionHistory: "Transaction history",
    noTransactions: "No transactions yet",
    spent: "Spent",
    toppedUp: "Top-up",
    sectionPremium: "Premium",
    sectionStandard: "Standard",
    sectionEconomy: "Economy",
    pricePerSeat: "Price",
    reservedSlot: "Reserved",
    selectCar: "Select a shared car",
    noCarOption: "No car",
    sharedCarReservation: "Shared Car Reservation",
    // Carpool offer
    departureDate: "Departure date",
    departureTime: "Departure time",
    rideOffered: "Ride offered!",
    myOfferedRides: "My offered rides",
    offeredRide: "Offered ride",
    seatsAvailable: "seats",
    // Cancellation
    cancelBooking: "Cancel booking",
    cancelRide: "Cancel ride",
    cancelConfirmTitle: "Cancel this booking?",
    cancelFreeDesc: "You are more than 24 hours before the start time. Cancellation is free.",
    cancelLateDesc: "Cancelling within 24 hours results in a €5 administrative fee. Do you wish to proceed?",
    keepBooking: "Keep booking",
    confirmCancel: "Confirm cancellation",
    cancellationFree: "Cancellation confirmed — no fee charged.",
    cancellationLate: "Cancelled — €5 administrative fee charged.",
    lateCancelFee: "Late cancellation fee",
  },
  nl: {
    welcome: "WELKOM BIJ HET MIJNSTADION",
    searchPlaceholder: "Zoek een ruimte, deelauto...",
    workspaces: "Werkplekken",
    sharedMobility: "Deelmobiliteit",
    neighborhoodEnergy: "Buurt & Energie",
    todaySaving: "VANDAAG: Buurt bespaart",
    inEnergy: "aan energie!",
    home: "Home",
    search: "Zoeken",
    bookings: "Boekingen",
    account: "Account",
    findRoom: "VIND EEN RUIMTE",
    capacity: "Capaciteit",
    noPreference: "Geen voorkeur",
    date: "Datum",
    time: "Tijd",
    reserve: "RESERVEER",
    bookThisRoom: "BOEK DEZE RUIMTE",
    bookingConfirm: "BOEKING BEVESTIGEN",
    bookingConfirmed: "BOEKING BEVESTIGD!",
    payAndBook: "BETALEN & BOEKEN",
    addMobility: "Voeg Deelmobiliteit toe?",
    addMobilityDesc: "Voeg deelmobiliteit opties toe.",
    paymentMethod: "Betaalmethode",
    digitalKey: "Digitale Sleutel",
    scanAtEntrance: "Scan bij Ingang",
    openSmartLock: "OPEN SLIMME SLOT",
    routeDescription: "ROUTEBESCHRIJVING",
    reserveSharedCar: "DEELAUTO RESERVEREN",
    hours: "uur",
    perHour: "/u",
    perRide: "per rit",
    free: "Gratis",
    offerForFree: "Gratis aanbieden",
    pricePerRide: "Prijs per rit (€)",
    confirmMobilityBooking: "Bevestig je boeking",
    confirmMobilityBookingDesc: "Controleer de gegevens hieronder voordat je bevestigt.",
    totalEstimated: "Totaal geschat",
    confirmBooking: "Bevestig Boeking",
    persons: "p",
    wifi: "Wi-Fi",
    projector: "Beamer",
    coffee: "Koffie & Dranken",
    tv: "TV",
    available: "Beschikbaar",
    occupied: "Bezet",
    maintenance: "Onderhoud",
    parkingSpaces: "Parkeerplaatsen vrij",
    eBikes: "E-bikes beschikbaar",
    evChargers: "EV-laders",
    solarOutput: "Zonne-energie",
    sharedWithNeighbors: "Gedeeld met buren",
    co2Saved: "CO₂ Bespaard Vandaag",
    surplus: "overschot beschikbaar",
    noMatchToday: "Geen wedstrijd vandaag — zonne-energie gedeeld met buurt",
    receiving: "Ontvangt",
    offline: "Offline",
    localNeighbours: "Lokale Buren",
    rent: "Huur",
    backToHome: "Terug",
    features: "Voorzieningen",
    location: "Locatie",
    stadiumEntrance: "Stadion ingang",
    login: "INLOGGEN",
    logout: "UITLOGGEN",
    loggedIn: "Ingelogd",
    email: "E-mail",
    password: "Wachtwoord",
    emailPlaceholder: "uw@email.com",
    passwordPlaceholder: "Uw wachtwoord",
    communityCenter: "Buurthuis",
    localSchool: "Buurtschool",
    residentialBlockA: "Woonblok A",
    sportsClinic: "Sportkliniek",
    cafeDistrict: "Caféwijk",
    northGate: "Noordpoort",
    eastWing: "Oostvleugel",
    southGate: "Zuidpoort",
    westVIP: "West VIP",
    stadiumMap: "Stadionplattegrond",
    mapHint: "Tik op een pin of hover over een item",
    facilityParking: "Parking",
    facilityBikeRack: "Fietsenstalling",
    facilityVipEntrance: "VIP-ingang",
    facilityFirstAid: "EHBO",
    standMain: "Hoofdtribune",
    standFamily: "Familietribune",
    standNorth: "Tribune Noord",
    standSouth: "Tribune Zuid",
    mapAvailableHere: "hier beschikbaar",
    inUse: "in gebruik",
    charging: "opladen",
    fullyCharged: "Volledig opgeladen",
    bike: "Fiets",
    electric: "Elektrisch",
    hybrid: "Hybride",
    noBookings: "Geen komende boekingen",
    noBookingsDesc: "Je geboekte ruimtes verschijnen hier.",
    noResults: "Geen resultaten gevonden",
    communityFeedback: "Community Feedback",
    feedbackPlaceholder: "Deel uw mening of bezorgdheid...",
    feedbackExample1: "De nieuwe laadstations bij de zuidpoort zijn geweldig!",
    feedbackExample2: "Kunnen we meer zonnepanelen op de oostvleugel krijgen?",
    feedbackExample3: "De deelfietsen hebben een beter onderhoudsschema nodig.",
    general: "Algemeen",
    facilities: "Voorzieningen",
    mobilityCategory: "Mobiliteit",
    energyCategory: "Energie",
    safety: "Veiligheid",
    you: "Jij",
    concerns: "Feedback",
    governancePortal: "MULTI-ACTOR GOVERNANCE PORTAAL",
    governanceDesc: "Samenwerking tussen belanghebbenden & KPI-overzicht",
    kpiRoomOccupancy: "Ruimtebezetting",
    kpiParkingUsage: "Parkeergebruik",
    kpiEnergyShared: "Energie Gedeeld",
    kpiActiveUsers: "Actieve Gebruikers",
    hubManager: "Hub Manager",
    cityCouncil: "Gemeenteraad",
    energyProvider: "Energieleverancier",
    mobilityPartner: "Mobiliteitspartner",
    communityRep: "Buurtvertegenwoordiger",
    roleOperations: "Operaties",
    rolePolicy: "Beleid & Planning",
    roleEnergy: "Energiebeheer",
    roleMobility: "Transport & Parkeren",
    roleCommunity: "Buurtrelaties",
    stakeholders: "Belanghebbenden",
    recentActivity: "Recente Activiteit",
    activityEnergy: "Zonne-overschot gedeeld met buurthuis",
    activityBooking: "VIP Loge geboekt voor bedrijfsevenement",
    activityFeedback: "Nieuwe community feedback ontvangen (3)",
    activityParking: "Oostvleugel parkeren op 40% capaciteit",
    username: "Gebruikersnaam",
    usernamePlaceholder: "Uw gebruikersnaam",
    invalidCredentials: "Ongeldige gebruikersnaam of wachtwoord. Probeer opnieuw.",
    wrongPassword: "Onjuist wachtwoord voor Hub Manager account.",
    dashboard: "Dashboard",
    hubManagerHint: "Hub Manager? Log in met uw gegevens voor het governance dashboard.",
    // Booking calendar
    calendarTitle: "Beschikbaarheidskalender",
    booked: "Geboekt",
    selectDate: "Selecteer een datum om beschikbaarheid te zien",
    slot: "Slot",
    bookSlot: "Boek",
    // Shared mobility
    sharedMobilitySection: "Deelmobiliteit",
    transportTypes: "Vervoerstypen",
    eBike: "E-Fiets",
    eScooter: "E-Scooter",
    sharedCar: "Deelauto",
    carpoolTitle: "Carpool",
    carpoolDesc: "Vind of bied ritten aan",
    findRide: "Rit zoeken",
    offerRide: "Rit aanbieden",
    rideFrom: "Van",
    rideTo: "Naar",
    rideWhen: "Wanneer",
    rideSeats: "Plaatsen",
    requestRide: "Rit aanvragen",
    rideRequested: "Rit aangevraagd!",
    bikeRented: "Fiets gehuurd! Ophalen bij",
    reserveCar: "Reserveer",
    carReserved: "Auto gereserveerd!",
    sharedCars: "Deelauto's",
    carsAvailable: "beschikbaar",
    // Reviews
    feedbackExample4: "Parkeren is vaak vol tijdens evenementen, meer capaciteit nodig.",
    feedbackExample5: "De VIP-loge is uitstekend voor zakelijke vergaderingen.",
    feedbackExample6: "Graag betere bewegwijzering voor de deelauto-plekken.",
    feedbackExample7: "Geweldig initiatief met zonne-energie delen!",
    feedbackExample8: "Veiligheidsverlichting op het oostparkeerterrein moet beter.",
    feedbackExample9: "De wifi in de coworking ruimte is zeer betrouwbaar.",
    feedbackExample10: "Kan er een pendeldienst naar het station komen?",
    allCategories: "Alle",
    // Chatbot
    chatbotTitle: "Stadion Assistent",
    chatbotPlaceholder: "Stel een vraag...",
    chatbotWelcome: "Hallo! Ik ben de Stadion Assistent. Hoe kan ik u helpen?",
    // Invite
    invitePeople: "Personen Uitnodigen",
    inviteDesc: "Nodig anderen uit voor het platform",
    inviteEmail: "E-mailadres",
    inviteEmailPlaceholder: "collega@email.com",
    inviteRole: "Rol",
    inviteUser: "Gebruiker",
    inviteManager: "Manager",
    sendInvite: "Uitnodiging Versturen",
    inviteSent: "Uitnodiging verstuurd!",
    inviteMessage: "Optioneel bericht",
    inviteMessagePlaceholder: "Doe mee op het stadionplatform!",
    // Directions
    directionsTitle: "Routebeschrijving",
    directionsFrom: "UHasselt Gebouw D, Diepenbeek",
    directionsTo: "Mijnstadion Beringen",
    openInMaps: "Open in Google Maps",
    // Carpool rides
    ride1From: "UHasselt",
    ride1To: "Mijnstadion",
    ride1Driver: "Thomas B.",
    ride1Time: "Morgen, 08:30",
    ride2From: "Station Hasselt",
    ride2To: "Mijnstadion",
    ride2Driver: "Sarah K.",
    ride2Time: "Morgen, 09:00",
    ride3From: "Genk Centrum",
    ride3To: "Mijnstadion",
    ride3Driver: "Pieter V.",
    ride3Time: "Woe, 14:00",
    // Mobility booking confirmation modal
    mobilityBookingConfirmed: "Boeking bevestigd!",
    mobilityBookingDesc: "Je reservering is toegevoegd aan je aankomende boekingen.",
    bikeBookingTitle: "E-Fiets reservering",
    carBookingTitle: "Deelauto reservering",
    rideBookingTitle: "Carpool rit",
    viewMyBookings: "Bekijk mijn boekingen",
    close: "Sluiten",
    pickADate: "Kies een datum",
    from: "Van",
    to: "Tot",
    invalidTimeRange: "Eindtijd moet na de starttijd liggen.",
    inviteToSession: "Personen uitnodigen voor deze sessie",
    inviteToSessionDesc: "Voeg collega's toe via e-mail — zij ontvangen een agenda-uitnodiging.",
    addInvitee: "Voeg toe",
    inviteesAdded: "genodigden toegevoegd",
    // Login gate
    loginWelcome: "Welkom bij het Mijnstadion",
    loginSubtitle: "Log in om verder te gaan",
    landingTagline: "Jouw stadionhub voor werkplekken, mobiliteit en energie.",
    signIn: "Inloggen",
    signUp: "Registreren",
    register: "Registreren",
    createAccount: "Maak je account aan",
    alreadyHaveAccount: "Heb je al een account?",
    noAccountYet: "Nog geen account?",
    fullName: "Volledige naam",
    fullNamePlaceholder: "Je naam",
    confirmPassword: "Bevestig wachtwoord",
    passwordsDontMatch: "Wachtwoorden komen niet overeen.",
    accountCreated: "Account aangemaakt — log in om verder te gaan.",
    userAlreadyExists: "Er bestaat al een account met deze gebruikersnaam.",
    backToWelcome: "Terug",
    // Room availability
    availableUnits: "beschikbaar",
    // Ticketshop
    ticketshop: "Ticketshop",
    ticketshopSubtitle: "Koop tickets en laad je kaart op",
    buyTickets: "Tickets Kopen",
    consumptionCard: "Consumptiekaart",
    football: "Voetbal",
    hockey: "Hockey",
    allSports: "Alles",
    seats: "plaatsen",
    buy: "Koop",
    clubConsumptionCard: "Club Consumptiekaart",
    currentBalance: "Huidig saldo",
    validForAllSports: "Geldig voor alle sporten — Voetbal, Hockey & meer.",
    topUpAmount: "Oplaadbedrag",
    customAmount: "Ander bedrag",
    enterAmount: "Voer bedrag in €",
    topUpNow: "Opladen",
    topUpConfirmed: "Kaart opgeladen",
    purchaseConfirmed: "Aankoop bevestigd!",
    matchFootball1: "KVK Beringen vs Lommel SK",
    matchFootball2: "KVK Beringen vs RC Hades",
    matchHockey1: "Beringen Hockey vs HC Hasselt",
    matchHockey2: "Beringen Hockey vs Genk HC",
    ticketshopShort: "Tickets",
    selectSeat: "Kies je plaats",
    section: "Vak",
    row: "Rij",
    seat: "Plaats",
    selectedSeat: "Geselecteerde plaats",
    pickSeatFirst: "Kies een vak, rij en plaats om verder te gaan",
    chatbotResponseParking: "Het stadion heeft 1.080 parkeerplaatsen verdeeld over 4 zones. Bekijk de sectie Deelmobiliteit voor real-time beschikbaarheid.",
    chatbotResponseRoom: "We hebben verschillende boekbare ruimtes waaronder VIP-loges, Persruimte A en de Werkplek Stadion. Ga naar Werkplekken om te boeken.",
    chatbotResponseEnergy: "De zonnepanelen van het stadion produceren tot 200 kW. Overtollige energie wordt gedeeld met 5 lokale buren in de buurt.",
    chatbotResponseBike: "We hebben 6 e-bikes beschikbaar op verschillende locaties. Bekijk het tabblad E-Fiets in Deelmobiliteit om er een te huren.",
    chatbotResponsePrice: "Ruimteprijzen variëren van €10/u (Werkplek) tot €25/u (Persruimte). VIP-loges starten vanaf €15/u.",
    chatbotResponseCarpool: "Carpool-ritten vind je onder Deelmobiliteit. Klik op de knop hieronder om er direct naartoe te gaan.",
    chatbotGoToCarpool: "Ga naar Carpool",
    chatbotFallback: "Ik kan vragen beantwoorden over parkeren, ruimtes, energie, fietsen, carpool en prijzen. Stel gerust een vraag!",
    // Ticketshop additions
    ticketshopMenu: "Ticketshop",
    upcomingBookings: "Aankomende boekingen",
    myTickets: "Mijn tickets",
    reserveSharedCarDesc: "Vind een beschikbare deelauto bij het stadion.",
    open: "Openen",
    notAvailable: "Niet beschikbaar",
    available_short: "Beschikbaar",
    bookedAlready: "Reeds geboekt voor dit tijdslot",
    confirmAndPay: "Bevestigen & betalen",
    paymentSummary: "Betaaloverzicht",
    total: "Totaal",
    item: "Item",
    payNow: "Nu betalen",
    cancel: "Annuleren",
    transactionHistory: "Transactiegeschiedenis",
    noTransactions: "Nog geen transacties",
    spent: "Besteed",
    toppedUp: "Opgeladen",
    sectionPremium: "Premium",
    sectionStandard: "Standaard",
    sectionEconomy: "Economy",
    pricePerSeat: "Prijs",
    reservedSlot: "Gereserveerd",
    selectCar: "Kies een deelauto",
    noCarOption: "Geen auto",
    sharedCarReservation: "Deelauto reservering",
    // Carpool offer
    departureDate: "Vertrekdatum",
    departureTime: "Vertrektijd",
    rideOffered: "Rit aangeboden!",
    myOfferedRides: "Mijn aangeboden ritten",
    offeredRide: "Aangeboden rit",
    seatsAvailable: "plaatsen",
    // Cancellation
    cancelBooking: "Boeking annuleren",
    cancelRide: "Rit annuleren",
    cancelConfirmTitle: "Deze boeking annuleren?",
    cancelFreeDesc: "Je bent meer dan 24 uur voor de starttijd. Annuleren is gratis.",
    cancelLateDesc: "Annuleren binnen 24 uur leidt tot een administratieve kost van €5. Wil je doorgaan?",
    keepBooking: "Behouden",
    confirmCancel: "Annulering bevestigen",
    cancellationFree: "Annulering bevestigd — geen kosten.",
    cancellationLate: "Geannuleerd — €5 administratieve kost aangerekend.",
    lateCancelFee: "Late annuleringskost",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("nl");

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};